# CONSTANTS
DIGITS = '0123456789'

# TOKENTYPE(TT) CONSTANTS
TT_INT = 'int'
TT_FLOAT = 'float'
TT_PLUS = '+'
TT_MINUS = '-'
TT_MUL = '*'
TT_DIV = '/'
TT_LPAREN = '('
TT_RPAREN = ')'
TT_EOF = 'EOF'
TT_POW = '^'
